apiVersion: v1
kind: Service
metadata:
  labels:
    run: redis-2
  name: redis-2
spec:
  type: NodePort
  ports:
  - port: 6379
    nodePort: 30002
    name: redis
  - port: 16379
    name: cluster
  selector:
    run: redis-2
