apiVersion: v1
kind: Service
metadata:
  labels:
    run: redis-3
  name: redis-3
spec:
  type: NodePort
  ports:
  - port: 6379
    nodePort: 30003
    name: redis
  - port: 16379
    name: cluster
  selector:
    run: redis-3
